"""empty message

Revision ID: c0246cb01079
Revises: ae5c0a6aebb3
Create Date: 2016-06-10 11:03:28.895867

"""

# revision identifiers, used by Alembic.
revision = 'c0246cb01079'
down_revision = 'ae5c0a6aebb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_itemrevision_created_date_item_id', 'itemrevision', ['date_created', 'item_id'], unique=False)
    op.drop_index('ix_itemrevision_date_created', table_name='itemrevision')
    op.create_index('ix_itemrevision_date_last_ephemeral_change_item_id', 'itemrevision', ['date_last_ephemeral_change', 'item_id'], unique=False)
    op.drop_index('ix_itemrevision_date_last_ephemeral_change', 'itemrevision', ['date_last_ephemeral_change'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_itemrevision_date_created', 'itemrevision', ['date_created'], unique=False)
    op.drop_index('ix_itemrevision_created_date_item_id', table_name='itemrevision')
    op.create_index('ix_itemrevision_date_last_ephemeral_change', 'itemrevision', ['date_last_ephemeral_change'], unique=False)
    op.drop_index('ix_itemrevision_date_last_ephemeral_change_item_id', 'itemrevision', ['date_last_ephemeral_change'])
    ### end Alembic commands ###
